[project]
name = "McChattie"
version = "0.1.0"
description = "A chat interface for OpenAI API."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.30.0",
    "boto3>=1.40.21",
    "chainlit>=2.6.5",
    "openai>=1.98.0",
]
