[project]
name = "McChattie"
version = "0.1.0"
description = "A chat interface for OpenAI API."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chainlit>=2.6.5",
    "openai>=1.98.0",
]
